// examples/angular/src/pages/ui/components/authenticator/sign-in-with-email/sign-in-with-email.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';
import { SignInProps } from '@aws-amplify/ui-angular';
import awsExports from './aws-exports';

@Component({
  selector: 'sign-in-with-email',
  templateUrl: 'sign-in-with-email.component.html',
})
export class SignInWithEmailComponent {
  constructor() {
    Amplify.configure(awsExports);
  }

  public getSignInProps(ctx: SignInProps): SignInProps {
    return { ...ctx, hideSignUp: true };
  }

  public formFields = {
    confirmVerifyUser: {
      confirmation_code: {
        label: 'New Label',
        placeholder: 'Enter your Confirmation Code:',
        isRequired: false,
      },
    },
  };
}

<amplify-authenticator [formFields]="formFields" [hideSignUp]="true">
  <ng-template amplifySlot="sign-in" let-ctx>
    <amplify-sign-in [ctx]="getSignInProps(ctx)"></amplify-sign-in>
  </ng-template>
</amplify-authenticator>

// examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import { Authenticator, SignIn } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
const formFields = {
  confirmVerifyUser: {
    confirmation_code: {
      label: 'New Label',
      placeholder: 'Enter your Confirmation Code:',
      isRequired: false,
    },
  },
};
const log = console.log;
</script>

<template>
  <authenticator :form-fields="formFields" :hide-sign-up="true">
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>

    <template v-slot:sign-in="{ signInProps }">
      <!-- <button class="amplify-button" @click="() => log(signInProps)">
        Log SignInProps
      </button>
      <br /> -->
      <sign-in v-bind="{ ...signInProps, hideSignUp: false }" />
    </template>
  </authenticator>
</template>
