// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts
import {
  AfterContentInit,
  ChangeDetectorRef,
  Component,
  ContentChildren,
  Input,
  OnDestroy,
  OnInit,
  QueryList,
  TemplateRef,
  ViewEncapsulation,
} from '@angular/core';
import {
  AuthenticatorMachineOptions,
  authenticatorTextUtil,
  configureComponent,
  defaultAuthHubHandler,
  listenToAuthHub,
  SocialProvider,
} from '@aws-amplify/ui';
import { AmplifySlotDirective } from '../../../../utilities/amplify-slot/amplify-slot.directive';
import { CustomComponentsService } from '../../../../services/custom-components.service';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { VERSION } from '../../../../../version';
import { SignInProps } from '../../types';

const { getSignInTabText, getSignUpTabText } = authenticatorTextUtil;

@Component({
  selector: 'amplify-authenticator',
  templateUrl: './authenticator.component.html',
  providers: [CustomComponentsService], // make sure custom components are scoped to this authenticator only
  encapsulation: ViewEncapsulation.None,
})
export class AuthenticatorComponent
  implements OnInit, AfterContentInit, OnDestroy
{
  @Input() formFields: AuthenticatorMachineOptions['formFields'];
  @Input() initialState: AuthenticatorMachineOptions['initialState'];
  @Input() loginMechanisms: AuthenticatorMachineOptions['loginMechanisms'];
  @Input() services: AuthenticatorMachineOptions['services'];
  @Input() signUpAttributes: AuthenticatorMachineOptions['signUpAttributes'];
  @Input() socialProviders: SocialProvider[];
  @Input() variation: 'default' | 'modal';
  @Input() hideSignUp: boolean;

  @ContentChildren(AmplifySlotDirective)
  private customComponentQuery: QueryList<AmplifySlotDirective> = null;

  // translated texts
  public signInTitle = getSignInTabText();
  public signUpTitle = getSignUpTabText();

  private hasInitialized = false;
  private isHandlingHubEvent = false;
  private unsubscribeMachine: () => void;
  private unsubscribeHub: ReturnType<typeof listenToAuthHub>;

  constructor(
    private authenticator: AuthenticatorService,
    private contextService: CustomComponentsService,
    private changeDetector: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    const {
      initialState,
      loginMechanisms,
      services,
      signUpAttributes,
      socialProviders,
      formFields,
    } = this;

    configureComponent({
      packageName: '@aws-amplify/ui-angular',
      version: VERSION,
    });

    const { authService, initializeMachine } = this.authenticator;

    this.unsubscribeHub = listenToAuthHub(
      authService,
      async (data, service) => {
        await defaultAuthHubHandler(data, service);
        /**
         * Hub events aren't properly caught by Angular, because they are
         * synchronous events. Angular tracks async network events and
         * html events, but not synchronous events like hub.
         *
         * On any notable hub events, we run change detection manually.
         */
        this.changeDetector.detectChanges();

        /**
         * Hub events that we handle can lead to multiple state changes:
         * e.g. `authenticated` -> `signOut` -> initialState.
         *
         * We want to ensure change detection runs all the way, until
         * we reach back to the initial state. Setting the below flag
         * to true to until we reach initial state.
         */
        this.isHandlingHubEvent = true;
      }
    );

    /**
     * Subscribes to state machine changes and sends INIT event
     * once machine reaches 'setup' state.
     */
    this.unsubscribeMachine = this.authenticator.subscribe(() => {
      const { route } = this.authenticator;

      if (this.isHandlingHubEvent) {
        this.changeDetector.detectChanges();

        const initialStateWithDefault = initialState ?? 'signIn';

        // We can stop manual change detection if we're back to the initial state
        if (route === initialStateWithDefault) {
          this.isHandlingHubEvent = false;
        }
      }

      if (!this.hasInitialized && route === 'setup') {
        initializeMachine({
          initialState,
          loginMechanisms,
          services,
          signUpAttributes,
          socialProviders,
          formFields,
        });

        this.hasInitialized = true;
      }
    }).unsubscribe;

    /**
     * handling translations after content init, because authenticator and its
     * translations might be initialized before the main app's `ngOnInit` is run.
     */
    this.signInTitle = getSignInTabText();
    this.signUpTitle = getSignUpTabText();
  }

  /**
   * Lifecycle Methods
   */
  ngAfterContentInit(): void {
    this.contextService.customComponents = this.mapCustomComponents(
      this.customComponentQuery
    );
  }

  ngOnDestroy(): void {
    if (this.unsubscribeMachine) this.unsubscribeMachine();
    if (this.unsubscribeHub) this.unsubscribeHub();
  }

  /**
   * Class Functions
   */

  // context passed to "authenticated" slot
  public get context() {
    return this.authenticator.slotContext;
  }

  public get signInProps(): { $implicit: SignInProps } {
    const {
      error,
      isPending,
      updateBlur,
      updateForm,
      submitForm,
      toFederatedSignIn,
      toSignUp,
      toResetPassword,
    } = this.authenticator;

    return {
      $implicit: {
        error,
        hideSignUp: false,
        isPending,
        handleBlur: updateBlur,
        handleChange: updateForm,
        handleSubmit: submitForm,
        toFederatedSignIn,
        toSignUp,
        toResetPassword,
      },
    };
  }

  public get route() {
    return this.authenticator.route;
  }

  public onTabChange() {
    const route = this.authenticator.route;
    if (route === 'signIn') {
      this.authenticator.toSignUp();
    } else {
      this.authenticator.toSignIn();
    }
  }

  public hasTabs() {
    const { route } = this.authenticator;
    return route === 'signIn' || route === 'signUp';
  }

  public hasRouteComponent() {
    const { route } = this.authenticator;

    switch (route) {
      case 'authenticated':
      case 'idle':
      case 'setup':
      case 'signOut':
      case 'transition':
        return false;
      default:
        return true;
    }
  }

  private mapCustomComponents(
    componentQuery: QueryList<AmplifySlotDirective>
  ): Record<string, TemplateRef<any>> {
    if (!componentQuery) return {};
    const customComponents: Record<string, TemplateRef<any>> = {};
    componentQuery.forEach((component) => {
      customComponents[component.name] = component.template;
    });

    return customComponents;
  }
}

<div
  data-amplify-authenticator
  [attr.data-variation]="variation"
  *ngIf="hasRouteComponent()"
>
  <div data-amplify-container>
    <amplify-slot name="header" [context]="context"></amplify-slot>
    <div
      data-amplify-router
      [attr.data-amplify-router-content]="hasTabs() ? undefined : ''"
    >
      <!-- <amplify-tabs
        (tabChange)="onTabChange()"
        *ngIf="(route === 'signIn' || route === 'signUp') && !hideSignUp"
      >
        <amplify-tab-item
          [title]="signInTitle"
          [active]="route === 'signIn'"
          data-amplify-router-content
        >
          signIn component
          <amplify-slot
            name="sign-in"
            [context]="signInProps"
            *ngIf="route === 'signIn'"
          >
          <amplify-sign-in [ctx]="signInProps" [test]="123"></amplify-sign-in>
          </amplify-slot>
        </amplify-tab-item>
        <amplify-tab-item
          [title]="signUpTitle"
          [active]="route === 'signUp'"
          data-amplify-router-content
        >
          <amplify-slot
            name="sign-up"
            [context]="context"
            *ngIf="route === 'signUp'"
          >
            <amplify-sign-up></amplify-sign-up>
          </amplify-slot>
        </amplify-tab-item>
      </amplify-tabs> -->

      <amplify-slot
        name="sign-in"
        [context]="signInProps"
        *ngIf="route === 'signIn'"
      >
        <amplify-sign-in [ctx]="signInProps"></amplify-sign-in>
      </amplify-slot>

      <amplify-slot
        name="sign-up"
        [context]="context"
        *ngIf="route === 'signUp'"
      >
        <amplify-sign-up></amplify-sign-up>
      </amplify-slot>

      <!-- confirmSignUp content -->
      <amplify-slot
        name="confirm-sign-up"
        [context]="context"
        *ngIf="route === 'confirmSignUp'"
      >
        <amplify-confirm-sign-up></amplify-confirm-sign-up>
      </amplify-slot>

      <!-- confirmSignIn content -->
      <amplify-slot
        name="confirm-sign-in"
        [context]="context"
        *ngIf="route === 'confirmSignIn'"
      >
        <amplify-confirm-sign-in></amplify-confirm-sign-in>
      </amplify-slot>

      <!-- setupTotp content -->
      <amplify-slot
        name="setup-totp"
        [context]="context"
        *ngIf="route === 'setupTOTP'"
      >
        <amplify-setup-totp></amplify-setup-totp>
      </amplify-slot>

      <!-- forceNewPassword content -->
      <amplify-slot
        name="force-new-password"
        [context]="context"
        *ngIf="route === 'forceNewPassword'"
      >
        <amplify-force-new-password></amplify-force-new-password>
      </amplify-slot>

      <!-- resetPassword content -->
      <amplify-slot
        name="reset-password"
        [context]="context"
        *ngIf="route === 'resetPassword'"
      >
        <amplify-reset-password></amplify-reset-password>
      </amplify-slot>

      <!-- confirmResetPassword content -->
      <amplify-slot
        name="confirm-reset-password"
        [context]="context"
        *ngIf="route === 'confirmResetPassword'"
      >
        <amplify-confirm-reset-password></amplify-confirm-reset-password>
      </amplify-slot>

      <!-- verifyUser content -->
      <amplify-slot
        name="verify-user"
        [context]="context"
        *ngIf="route === 'verifyUser'"
      >
        <amplify-verify-user></amplify-verify-user>
      </amplify-slot>

      <!-- confirmVerifyUser content -->
      <amplify-slot
        name="confirm-verify-user"
        [context]="context"
        *ngIf="route === 'confirmVerifyUser'"
      >
        <amplify-confirm-verify-user></amplify-confirm-verify-user>
      </amplify-slot>
    </div>

    <amplify-slot name="footer" [context]="context"></amplify-slot>
  </div>
</div>

<!-- signedIn content is rendered outside authenticator so it's not styled by authenticator -->
<amplify-slot
  name="authenticated"
  [context]="context"
  *ngIf="route === 'authenticated'"
>
  <ng-content></ng-content>
</amplify-slot>

// packages/vue/src/components/authenticator.vue
<script setup lang="ts">
import { useAuth, useAuthenticator } from '../composables/useAuth';
import { createSharedComposable } from '@vueuse/core';
import {
  ref,
  toRefs,
  computed,
  useAttrs,
  watch,
  Ref,
  onMounted,
  onUnmounted,
} from 'vue';
import { useActor, useInterpret } from '@xstate/vue';
import {
  AmplifyUser,
  AuthenticatorMachineOptions,
  authenticatorTextUtil,
  AuthFormFields,
  createAuthenticatorMachine,
  getActorState,
  getServiceFacade,
  listenToAuthHub,
  SocialProvider,
  configureComponent,
} from '@aws-amplify/ui';

import SignIn, { SignInProps } from './sign-in.vue';
import SignUp from './sign-up.vue';
import ConfirmSignUp from './confirm-sign-up.vue';
import ConfirmSignIn from './confirm-sign-in.vue';
import SetupTotp from './setup-totp.vue';
import ForceNewPassword from './force-new-password.vue';
import ResetPassword from './reset-password.vue';
import ConfirmResetPassword from './confirm-reset-password.vue';
import VerifyUser from './verify-user.vue';
import ConfirmVerifyUser from './confirm-verify-user.vue';
import { VERSION } from '../version';

const attrs = useAttrs();

const props = withDefaults(
  defineProps<{
    hideSignUp?: boolean;
    initialState?: AuthenticatorMachineOptions['initialState'];
    loginMechanisms?: AuthenticatorMachineOptions['loginMechanisms'];
    services?: AuthenticatorMachineOptions['services'];
    signUpAttributes?: AuthenticatorMachineOptions['signUpAttributes'];
    variation?: 'default' | 'modal';
    socialProviders?: SocialProvider[];
    formFields?: AuthFormFields;
  }>(),
  {
    variation: 'default',
  }
);

const {
  initialState,
  loginMechanisms,
  variation,
  services,
  signUpAttributes,
  socialProviders,
  hideSignUp,
  formFields,
} = toRefs(props);

const emit = defineEmits([
  'signInSubmit',
  'confirmSignUpSubmit',
  'resetPasswordSubmit',
  'confirmResetPasswordSubmit',
  'confirmSignInSubmit',
  'mSetupTOTPSubmit',
  'forceNewPasswordSubmit',
  'signUpSubmit',
  'verifyUserSubmit',
  'confirmVerifyUserSubmit',
]);
const machine = createAuthenticatorMachine();

const service = useInterpret(machine);
let unsubscribeHub: () => void;
let unsubscribeMachine: () => void;

const { state, send } = useActor(service);
useAuth(service);

const useAuthShared = createSharedComposable(useAuthenticator);
const facade = useAuthShared();

const hasInitialized = ref(false);

const signInProps = computed(() => {
  const {
    error,
    isPending,
    updateBlur,
    updateForm,
    submitForm,
    toFederatedSignIn,
    toSignUp,
    toResetPassword,
  } = facade;

  return {
    error,
    isPending,
    handleBlur: updateBlur,
    handleChange: updateForm,
    handleSubmit: submitForm,
    toFederatedSignIn,
    toSignUp,
    toResetPassword,
  } as unknown as SignInProps;
});

/**
 * Subscribes to state machine changes and sends INIT event
 * once machine reaches 'setup' state.
 */
unsubscribeMachine = service.subscribe((newState) => {
  if (newState.matches('setup') && !hasInitialized.value) {
    send({
      type: 'INIT',
      data: {
        initialState: initialState?.value,
        loginMechanisms: loginMechanisms?.value,
        socialProviders: socialProviders?.value,
        signUpAttributes: signUpAttributes?.value,
        services: services?.value,
        formFields: formFields?.value,
      },
    });
    hasInitialized.value = true;
  }
}).unsubscribe;

onMounted(() => {
  unsubscribeHub = listenToAuthHub(service);
  configureComponent({
    packageName: '@aws-amplify/ui-vue',
    version: VERSION,
  });
});

onUnmounted(() => {
  if (unsubscribeHub) unsubscribeHub();
  if (unsubscribeMachine) unsubscribeMachine();
});

const actorState = computed(() => getActorState(state.value));

const signInComponent = ref();
const signUpComponent = ref();
const confirmSignUpComponent = ref();
const confirmSignInComponent = ref();
const confirmSetupTOTPComponent = ref();
const forceNewPasswordComponent = ref();
const resetPasswordComponent = ref();
const confirmResetPasswordComponent = ref();
const verifyUserComponent = ref();
const confirmVerifyUserComponent = ref();

// text util
const { getSignInTabText, getSignUpTabText } = authenticatorTextUtil;

// computed
const signInLabel = computed(() => getSignInTabText());
const createAccountLabel = computed(() => getSignUpTabText());

//methods

const onSignInSubmitI = (e: Event) => {
  if (attrs?.onSignInSubmit) {
    emit('signInSubmit', e);
  } else {
    signInComponent.value?.submit(e);
  }
};

const onConfirmSignUpSubmitI = (e: Event) => {
  if (attrs?.onConfirmSignUpSubmit) {
    emit('confirmSignUpSubmit', e);
  } else {
    confirmSignUpComponent.value.submit(e);
  }
};

const onResetPasswordSubmitI = (e: Event) => {
  if (attrs?.onResetPasswordSubmit) {
    emit('resetPasswordSubmit', e);
  } else {
    resetPasswordComponent.value.submit(e);
  }
};

const onConfirmResetPasswordSubmitI = (e: Event) => {
  if (attrs?.onConfirmResetPasswordSubmit) {
    emit('confirmResetPasswordSubmit', e);
  } else {
    confirmResetPasswordComponent.value.submit(e);
  }
};

const onConfirmSignInSubmitI = (e: Event) => {
  if (attrs?.onConfirmSignInSubmit) {
    emit('confirmSignInSubmit', e);
  } else {
    confirmSignInComponent.value.submit(e);
  }
};

const onConfirmSetupTOTPSubmitI = (e: Event) => {
  if (attrs?.onForceNewPasswordSubmit) {
    emit('mSetupTOTPSubmit', e);
  } else {
    confirmSetupTOTPComponent.value.submit(e);
  }
};

const onForceNewPasswordSubmitI = (e: Event) => {
  if (attrs?.onForceNewPasswordSubmit) {
    emit('forceNewPasswordSubmit', e);
  } else {
    forceNewPasswordComponent.value.submit(e);
  }
};

const onSignUpSubmitI = (e: Event) => {
  if (attrs?.onSignUpSubmit) {
    emit('signUpSubmit', e);
  } else {
    signUpComponent.value.submit();
  }
};

const onVerifyUserSubmitI = (e: Event) => {
  if (attrs?.onVerifyUserSubmit) {
    emit('verifyUserSubmit', e);
  } else {
    verifyUserComponent.value.submit(e);
  }
};

const onConfirmVerifyUserSubmitI = (e: Event) => {
  if (attrs?.onConfirmVerifyUserSubmit) {
    emit('confirmVerifyUserSubmit', e);
  } else {
    confirmVerifyUserComponent.value.submit(e);
  }
};

// watchers

/**
 * Update service facade when context updates
 */

const user: Ref<AmplifyUser | null> = ref(null);
const signOut = ref();

watch(
  () => state.value.context,
  () => {
    const { user: u, signOut: s } = getServiceFacade({
      send,
      state: state.value,
    });
    user.value = u;
    signOut.value = s;
  }
);

const hasTabs = computed(() => {
  return (
    actorState.value?.matches('signIn') || actorState.value?.matches('signUp')
  );
});

const hasRouteComponent = computed(() => {
  return !(
    state.value.matches('authenticated') ||
    state.value.matches('idle') ||
    state.value.matches('setup') ||
    state.value.matches('signOut') ||
    actorState.value?.matches('autoSignIn')
  );
});

const logValidationError = () => console.log(signInProps.value);
const log = console.log;
</script>

<template>
  <button @click="logValidationError">asdfasdf</button>
  <div
    v-bind="$attrs"
    data-amplify-authenticator
    :data-variation="variation"
    v-if="hasRouteComponent"
  >
    <div data-amplify-container>
      <slot name="header"> </slot>
      <div
        data-amplify-router
        :data-amplify-router-content="hasTabs ? undefined : ''"
      >
        <base-two-tabs v-if="hasTabs && !hideSignUp">
          <base-two-tab-item
            :active="actorState?.matches('signIn')"
            :id="44472"
            :label="signInLabel"
            @click="send('SIGN_IN')"
          />
          <base-two-tab-item
            :active="actorState?.matches('signUp')"
            :id="44471"
            :label="createAccountLabel"
            @click="send('SIGN_UP')"
          />
        </base-two-tabs>
        <div v-if="hasTabs" data-amplify-router-content>
          <sign-in
            v-if="actorState?.matches('signIn')"
            @sign-in-submit="onSignInSubmitI"
            ref="signInComponent"
            v-bind="signInProps"
          >
            <template #signInSlotI>
              <slot name="sign-in" :signInProps="signInProps"></slot>
            </template>

            <template
              #form="{ info, onSignInSubmit, onForgotPasswordClicked, onInput }"
            >
              <slot
                name="sign-in-form"
                :info="info"
                :onInput="onInput"
                :onSignInSubmit="onSignInSubmit"
                :onForgotPasswordClicked="onForgotPasswordClicked"
              ></slot>
            </template>

            <template #header>
              <slot name="sign-in-header"></slot>
            </template>

            <template #footer>
              <slot name="sign-in-footer"> </slot>
            </template>
          </sign-in>
          <sign-up
            v-if="actorState?.matches('signUp') && !hideSignUp"
            @sign-up-submit="onSignUpSubmitI"
            ref="signUpComponent"
          >
            <template #signUpSlotI>
              <slot name="sign-up"></slot>
            </template>
            <template #header>
              <slot name="sign-up-header"></slot>
            </template>
            <template #signup-fields="{ info }">
              <slot name="sign-up-fields" :info="info"></slot>
            </template>

            <template #footer>
              <slot name="sign-up-footer"> </slot>
            </template>
          </sign-up>
        </div>

        <confirm-sign-up
          v-if="actorState?.matches('confirmSignUp')"
          @confirm-sign-up-submit="onConfirmSignUpSubmitI"
          ref="confirmSignUpComponent"
        >
          <template #confirmSignUpSlotI>
            <slot name="confirm-sign-up"></slot>
          </template>
          <template #header>
            <slot name="confirm-sign-up-header"></slot>
          </template>
          <template #footer="{ onConfirmSignUpSubmit, onLostCodeClicked }">
            <slot
              name="confirm-sign-up-footer"
              :onConfirmSignUpSubmit="onConfirmSignUpSubmit"
              :onLostCodeClicked="onLostCodeClicked"
            >
            </slot>
          </template>
        </confirm-sign-up>

        <reset-password
          v-if="actorState?.matches('resetPassword')"
          @reset-password-submit="onResetPasswordSubmitI"
          ref="resetPasswordComponent"
        >
          <template #resetPasswordSlotI>
            <slot name="reset-password"></slot>
          </template>
          <template #header>
            <slot name="reset-password-header"></slot>
          </template>
          <template #footer="{ onResetPasswordSubmit, onBackToSignInClicked }">
            <slot
              name="reset-password-footer"
              :onResetPasswordSubmit="onResetPasswordSubmit"
              :onBackToSignInClicked="onBackToSignInClicked"
            >
            </slot>
          </template>
        </reset-password>

        <confirm-reset-password
          v-if="actorState?.matches('confirmResetPassword')"
          @confirm-reset-password-submit="onConfirmResetPasswordSubmitI"
          ref="confirmResetPasswordComponent"
        >
          <template #confirmResetPasswordSlotI>
            <slot name="confirm-reset-password"></slot>
          </template>
          <template #header>
            <slot name="confirm-reset-password-header"></slot>
          </template>
          <template
            #footer="{ onConfirmResetPasswordSubmit, onLostYourCodeClicked }"
          >
            <slot
              name="confirm-reset-password-footer"
              :onConfirmResetPasswordSubmit="onConfirmResetPasswordSubmit"
              :onLostYourCodeClicked="onLostYourCodeClicked"
            >
            </slot>
          </template>
        </confirm-reset-password>

        <confirm-sign-in
          v-if="actorState?.matches('confirmSignIn')"
          @confirm-sign-in-submit="onConfirmSignInSubmitI"
          ref="confirmSignInComponent"
        >
          <template #confirmSignInSlotI>
            <slot name="confirm-sign-in"></slot>
          </template>
          <template #header>
            <slot name="confirm-sign-in-header"></slot>
          </template>
          <template #footer="{ onConfirmSignInSubmit, onBackToSignInClicked }">
            <slot
              name="confirm-sign-in-footer"
              :onConfirmSignInSubmit="onConfirmSignInSubmit"
              :onBackToSignInClicked="onBackToSignInClicked"
            >
            </slot>
          </template>
        </confirm-sign-in>

        <setup-totp
          v-if="
            actorState?.matches('setupTOTP.edit') ||
            actorState?.matches('setupTOTP.submit')
          "
          @confirm-setup-totp-submit="onConfirmSetupTOTPSubmitI"
          ref="confirmSetupTOTPComponent"
        >
          <template #confirmSetupTOTPI>
            <slot name="setup-totp"></slot>
          </template>
          <template #header>
            <slot name="setup-totp-header"></slot>
          </template>
          <template #footer="{ onSetupTOTPSubmit, onBackToSignInClicked }">
            <slot
              name="setup-totp-footer"
              :onSetupTOTPSubmit="onSetupTOTPSubmit"
              :onBackToSignInClicked="onBackToSignInClicked"
            >
            </slot>
          </template>
        </setup-totp>

        <force-new-password
          v-if="actorState?.matches('forceNewPassword')"
          @force-new-password-submit="onForceNewPasswordSubmitI"
          ref="forceNewPasswordComponent"
        >
          <template #forceNewPasswordI>
            <slot name="force-new-password"></slot>
          </template>
          <template #header>
            <slot name="force-new-password-header"></slot>
          </template>
          <template #force-new-password-form-fields>
            <slot name="force-new-password-form-fields"></slot>
          </template>
          <template
            #footer="{ onHaveAccountClicked, onForceNewPasswordSubmit }"
          >
            <slot
              name="force-new-password-footer"
              :onForceNewPasswordSubmit="onForceNewPasswordSubmit"
              :onBackToSignInClicked="onHaveAccountClicked"
            >
            </slot>
          </template>
        </force-new-password>

        <verify-user
          v-if="actorState?.matches('verifyUser')"
          @verify-user-submit="onVerifyUserSubmitI"
          ref="verifyUserComponent"
        >
          <template #verifyUserSlotI>
            <slot name="verify-user"></slot>
          </template>
          <template #header>
            <slot name="verify-user-header"></slot>
          </template>
          <template #footer="{ onVerifyUserSubmit, onSkipClicked }">
            <slot
              name="verify-user-footer"
              :onVerifyUserSubmit="onVerifyUserSubmit"
              :onSkipClicked="onSkipClicked"
            >
            </slot>
          </template>
        </verify-user>

        <confirm-verify-user
          v-if="actorState?.matches('confirmVerifyUser')"
          @confirm-verify-user-submit="onConfirmVerifyUserSubmitI"
          ref="confirmVerifyUserComponent"
        >
          <template #confirmVerifyUserSlotI>
            <slot name="confirm-verify-user"></slot>
          </template>
          <template #header>
            <slot name="confirm-verify-user-header"></slot>
          </template>
          <template #footer="{ onConfirmVerifyUserSubmit, onSkipClicked }">
            <slot
              name="confirm-verify-user-footer"
              :onConfirmVerifyUserSubmit="onConfirmVerifyUserSubmit"
              :onSkipClicked="onSkipClicked"
            >
            </slot>
          </template>
        </confirm-verify-user>
      </div>
      <slot name="footer"></slot>
    </div>
  </div>
  <slot
    v-if="state?.matches('authenticated')"
    :user="user"
    :state="state"
    :signOut="signOut"
    :send="send"
  ></slot>
</template>
