// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.ts
import {
  Component,
  HostBinding,
  Input,
  OnInit,
  ViewEncapsulation,
} from '@angular/core';
import {
  authenticatorTextUtil,
  getFormDataFromEvent,
  FormFieldsArray,
} from '@aws-amplify/ui';
import { SignInProps } from '../../types';

const { getForgotPasswordText, getSignInText } = authenticatorTextUtil;

@Component({
  selector: 'amplify-sign-in',
  templateUrl: './sign-in.component.html',
  encapsulation: ViewEncapsulation.None,
})
export class SignInComponent implements OnInit {
  @HostBinding('attr.data-amplify-authenticator-signin') dataAttr = '';
  @Input() ctx!: SignInProps;

  public forgotPasswordText = getForgotPasswordText();
  public signInButtonText = getSignInText();
  public sortedFormFields: FormFieldsArray;

  ngOnInit(): void {}

  public get context() {
    return {};
  }

  onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.ctx.handleBlur({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.ctx.handleSubmit(
      getFormDataFromEvent(event) as Record<string, string>
    );
  }
}

<amplify-slot name="sign-in-header" [context]="context"></amplify-slot>

<form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
  <amplify-federated-sign-in></amplify-federated-sign-in>
  <fieldset
    class="amplify-flex amplify-authenticator__column"
    style="flex-direction: column"
    data-amplify-fieldset
    [disabled]="ctx.isPending"
  >
    <legend class="amplify-visually-hidden">Sign in</legend>
    <amplify-base-form-fields route="signIn"></amplify-base-form-fields>
    <button
      amplify-button
      variation="primary"
      fullWidth="true"
      type="submit"
      [isDisabled]="ctx.isPending"
    >
      {{ signInButtonText }}
    </button>

    <amplify-error *ngIf="ctx.error">
      {{ authenticator.error }}
    </amplify-error>
  </fieldset>
</form>

<amplify-slot name="sign-in-footer" [context]="context">
  <div data-amplify-footer>
    <button
      amplify-button
      fontWeight="normal"
      size="small"
      variation="link"
      fullWidth="true"
      (click)="ctx.toResetPassword()"
    >
      {{ forgotPasswordText }}
    </button>
    <button
      amplify-button
      fontWeight="normal"
      size="small"
      variation="link"
      fullWidth="true"
      (click)="ctx.toSignUp()"
      *ngIf="!ctx.hideSignUp"
    >
      Sign up
    </button>
  </div>
</amplify-slot>

// packages/vue/src/components/sign-in.vue
<script setup lang="ts">
import { computed, ComputedRef, toRefs, useAttrs } from 'vue';

import {
  authenticatorTextUtil,
  getActorState,
  getFormDataFromEvent,
  SignInState,
  translate,
} from '@aws-amplify/ui';

import { useAuth } from '../composables/useAuth';
import FederatedSignIn from './federated-sign-in.vue';
import BaseFormFields from './primitives/base-form-fields.vue';

export interface SignInProps {
  error?: string;
  isPending: boolean;
  handleBlur: (data: Record<string, string>) => void;
  handleChange: (data: Record<string, string>) => void;
  handleSubmit: (data: Record<string, string>) => void;
  hideSignUp: boolean;
  toFederatedSignIn: () => void;
  toResetPassword: () => void;
  toSignUp: () => void;
}

const props = defineProps<SignInProps>();
const { handleChange, handleSubmit, hideSignUp } = toRefs(props);

const attrs = useAttrs();
const emit = defineEmits([
  'signInSubmit',
  'forgotPasswordClicked',
  'createAccountClicked',
]);

// Text Util
const { getForgotPasswordText, getSignInText, getSigningInText } =
  authenticatorTextUtil;

// Computed Properties
const forgotYourPasswordLink = computed(() => getForgotPasswordText());
const signInButtonText = computed(() => getSignInText());
const signIngButtonText = computed(() => getSigningInText());

const { state, send } = useAuth();
const actorState = computed(() =>
  getActorState(state.value)
) as ComputedRef<SignInState>;

// Methods

const onInput = (e: Event): void => {
  const { name, value } = e.target as HTMLInputElement;
  handleChange.value({ name, value });
};

const onSignInSubmit = (e: Event): void => {
  if (attrs?.onSignInSubmit) {
    emit('signInSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  handleSubmit.value(getFormDataFromEvent(e) as Record<string, string>);
};

const onForgotPasswordClicked = (): void => {
  if (attrs?.onForgotPasswordClicked) {
    emit('forgotPasswordClicked');
  } else {
    send({ type: 'RESET_PASSWORD' });
  }
};
</script>

<template>
  <slot v-bind="$attrs" name="signInSlotI">
    <slot name="header"></slot>

    <base-wrapper v-bind="$attrs">
      <base-form
        data-amplify-authenticator-signin
        @input="onInput"
        @submit.prevent="onSignInSubmit"
        method="post"
      >
        <template #formt="{ slotData }">
          <slot
            name="form"
            :info="slotData"
            :onSignInSubmit="onSignInSubmit"
            :onInput="onInput"
            :onForgotPasswordClicked="onForgotPasswordClicked"
          >
          </slot>
        </template>
        <federated-sign-in></federated-sign-in>
        <base-wrapper class="amplify-flex amplify-authenticator__column">
          <base-field-set
            :disabled="actorState.matches('signIn.submit')"
            class="amplify-flex amplify-authenticator__column"
          >
            <template #fieldSetI="{ slotData }">
              <slot name="signin-fields" :info="slotData"> </slot>
            </template>
            <legend class="amplify-visually-hidden">Sign in</legend>
            <base-form-fields route="signIn"></base-form-fields>
          </base-field-set>
          <base-alert v-if="actorState.context.remoteError">
            {{ translate(actorState.context.remoteError) }}
          </base-alert>

          <amplify-button
            :disabled="actorState.matches('signIn.submit')"
            class="amplify-field-group__control amplify-authenticator__font"
            :fullwidth="true"
            :loading="false"
            :variation="'primary'"
          >
            {{
              actorState.matches('signIn.submit')
                ? signIngButtonText
                : signInButtonText
            }}
          </amplify-button>
        </base-wrapper>
      </base-form>
    </base-wrapper>

    <base-footer>
      <slot name="footer">
        <div data-amplify-footer>
          <base-wrapper class="amplify-flex amplify-authenticator__column">
            <amplify-button
              @click="onForgotPasswordClicked"
              class="amplify-field-group__control amplify-authenticator__font"
              :variation="'link'"
              :fullwidth="true"
              :size="'small'"
              style="font-weight: normal"
              type="button"
            >
              {{ forgotYourPasswordLink }}
            </amplify-button>
            <amplify-button
              @click="toSignUp"
              v-if="!hideSignUp"
              class="amplify-field-group__control amplify-authenticator__font"
              :variation="'link'"
              :fullwidth="true"
              :size="'small'"
              style="font-weight: normal"
              type="button"
            >
              Sign Up
            </amplify-button>
          </base-wrapper>
        </div>
      </slot>
    </base-footer>
  </slot>
</template>
